import os
import re
from typing import List, Tuple


def transpile_lumos_to_js(lumos_code: str) -> str:
    regex_suffix = r'\b(?![^"]*")(?=(?:[^"]*"[^"]*")*[^"]*$)'

    rules: List[Tuple[str, str]] = [
        (r"set" + regex_suffix, "let"),
        (r"func" + regex_suffix, "function"),
        (r"print\(" + regex_suffix, "console.log("),
    ]

    js_code = lumos_code
    for pattern, replacement in rules:
        js_code = re.sub(pattern, replacement, js_code)

    return js_code


def run_lumos_compiler():
    if not lumos.is_saved():  # type: ignore
        lumos.show_warning("Compiler Error", "Please save the current file before compiling.")  # type: ignore
        return

    filepath = lumos.get_current_file()  # type: ignore
    if not filepath or not filepath.endswith((".lumos", ".lms")):
        lumos.show_warning("Compiler Error", "The active file is not a valid LumosScript file (.lumos, .lms).")  # type: ignore
        return

    project_dir = lumos.get_project_dir()  # type: ignore
    if not project_dir:
        lumos.show_warning("Compiler Error", "Please open a project folder to use the compiler.")  # type: ignore
        return

    try:
        relative_path = os.path.relpath(filepath, project_dir)

        lumos_code = lumos.read_project_file(relative_path)  # type: ignore

        js_code = transpile_lumos_to_js(lumos_code)

        header = f"// Compiled from {os.path.basename(filepath)}\n// Do not edit this file directly.\n\n"
        final_js_code = header + js_code

        output_filename = os.path.splitext(relative_path)[0] + ".js"

        lumos.write_project_file(output_filename, final_js_code)  # type: ignore

        lumos.show_message("LumosScript Compiler", f"Successfully compiled to {output_filename}!")  # type: ignore

    except Exception as e:
        lumos.show_error("Compiler Error", f"An unexpected error occurred during compilation:\n\n{e}")  # type: ignore


lumos.plugin_manager.add_menu_action(  # type: ignore
    menu_name="Tools",
    text="Compile LumosScript",
    callback=run_lumos_compiler,
    shortcut="Ctrl+Alt+A",
)
